FROM mcr.microsoft.com/devcontainers/go:1-${templateOption:imageVariant}


# Install Tools
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get install -y <packages> \
#     && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | sh \
    && mv nats /usr/local/bin


# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment the next lines to use go get to install anything else you need
# USER vscode
# RUN go get -x <your-dependency-or-tool>
# USER root

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1