FROM mcr.microsoft.com/devcontainers/php:1-8.2-bookworm


# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends python3-poetry python3-dev